name: SonarCloud Analysis With Code Coverage

on:
  workflow_run:
    workflows: ["Build and Test .NET"]
    types:
      - completed

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore ./src

      - name: Setup sonar scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Run tests with Coverage
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Begin SonarCloud analysis
        run: |
          dotnet sonarscanner begin \
            /k:"lncodes_singleton-design-pattern-csharp" \
            /o:"lncodes" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths=./TestResults/*/coverage.cobertura.xml


      - name: Build Project for Analysis
        run: dotnet build ./src --configuration Release --no-restore

      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
